###

GET http://localhost:9000/people
Content-Type: "application/json";

###
GET http://localhost:9000/people/
Content-Type: "application/json";

###
GET http://localhost:9000/person/g
Content-Type: "application/json";

###
POST http://localhost:9000/person/
Content-Type: application/json

{
  "primernombre": "Alberto",
  "primerapellido": "Luna",
  "fechadenacimiento": "2024-10-12" 
}

###
PUT http://localhost:9000/person/6be380f6-1451-482f-81e6-d43b945e631f
Content-Type: application/json

{
  "primernombre": "modificaicon3",
  "primerapellido": "2",
  "fechadenacimiento": "2024-03-21"
}

###
DELETE http://localhost:9000/person/
Content-Type: "application/json";