###

GET http://localhost:9000/people
Content-Type: "application/json";

###
GET http://localhost:9000/people/9
Content-Type: "application/json";

###
GET http://localhost:9000/person/9bec56aa-d7af-4fad-95ce-56823a6d23bb
Content-Type: "application/json";

###
POST http://localhost:9000/person/
Content-Type: application/json

{
  "primernombre": "usuarionuevo",
  "primerapellido": "de prueba",
  "fechadenacimiento": "2024-10-31" 
}

###
PUT http://localhost:9000/person/f49dbc5d-5cc1-4bfa-8b16-9012dc738c69
Content-Type: application/json

{
  "primernombre": "test User",
  "primerapellido": "nuevo dos",
  "fechadenacimiento": "2024-02-21"
}

###
DELETE http://localhost:9000/person/06301cb1-e260-40ba-91fd-445a4c2ccae9
Content-Type: "application/json";